# Generated by Django 3.2.8 on 2021-10-10 18:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=20), size=7)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobilenumber', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TurfBooked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('selected_date', models.CharField(max_length=200)),
                ('current_date', models.CharField(max_length=200)),
                ('booking_time', models.CharField(default='', max_length=200)),
                ('slots', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=200), size=20)),
            ],
        ),
        migrations.CreateModel(
            name='turfBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.CharField(max_length=12)),
                ('isBooked', models.BooleanField(default=False)),
                ('days', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
